### PR TITLE
Switch Kubernetes version from 1.1.3 to 1.2.4

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
1.2.4 is the latest on the 1.2 line.

### CODE REVIEW

**Comment by caseydavenport** [comment]
@MikeSpreitzer - Thanks for this :)

Will tag as k8s-1.2-docs once merged.  We're still sorting out CLA process for Tigera (should be done in the next couple of days), so we can merge once that is done.

**Comment by MikeSpreitzer** [comment]
Yeah, I was hoping that changing a version number doesn't require much of a process :-)

**Comment by MikeSpreitzer** [comment]
I have done some sniff testing of this, and it seems to be working so far.

**Comment by caseydavenport** [comment]
> Yeah, I was hoping that changing a version number doesn't require much of a process :-)

Yep, hopefully the process we just put in place isn't too onerous ;) - it's meant to be simple.  You can get to it from the license/cla check "details".

**Comment by caseydavenport** [comment]
@MikeSpreitzer I can't merge this guy until you've signed the CLA.  It should be very quick.

**Comment by MikeSpreitzer** [comment]
My company does not do formalities quickly.  I will ping someone about this...

**Comment by MikeSpreitzer** [comment]
I still have not finished wrangling lawyers.  BTW, this is outdated now --- 1.2.5 is out.  Perhaps some CLA-compliant person should just do the updated to 1.2.5

**Comment by caseydavenport** [comment]
@MikeSpreitzer - Yep, I understand ;) 

I'll run with this - I think we might be moving where these files live in the near future anyway.  Thanks.

**Pull request closed without merging**
