### PR TITLE
Don't assign IPv6 address when using calico-ipam

### PR DESCRIPTION
**Pull request by tomdee**
IPv6 isn't enabled by default on some hosts.

We should make it a user configurable option to turn it on.

### CODE REVIEW

**Comment by caseydavenport** [comment]
> We should make it a user configurable option to turn it on.

Why don't we just do this rather than rip out all the ipv6?

**Comment by tomdee** [comment]
I'm not ripping it all out. I'm just telling our IPAM not to allocate IPv6 since we are not in a position to use the result. I don't have time for a more complete solution so I'd like to get this in as is.

**Comment by caseydavenport** [comment]
Sure, if you think a more complete solution would take too much time that's fine.

My first impression was that making this configurable would have been two, maybe three lines of code, but perhaps there is more to it.

LGTM.

**Comment by tomdee** [comment]
Easy to do as another PR then :smile:

**Pull request merged**
